# Generated by Django 5.2.17 on 2026-09-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('service_type', models.CharField(choices=[('one_time', 'Разова допомога'), ('ongoing', 'Постійний супровід')], default='one_time', max_length=20, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('format_note', models.CharField(default='Відповідь надається письмово. Вартість — за запитом.', max_length=255, verbose_name='Примітка про формат/ціну')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Послуга (консультації)',
                'verbose_name_plural': 'Послуги та консультації',
                'ordering': ['service_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('zamovnykam', 'Замовникам'), ('uchasnykam', 'Учасникам')], max_length=20, verbose_name='Розділ')),
                ('title', models.CharField(max_length=255, verbose_name='Назва послуги')),
                ('slug', models.SlugField(blank=True, max_length=280)),
                ('short_description', models.CharField(blank=True, max_length=400, verbose_name='Короткий опис (для картки)')),
                ('whats_included', models.TextField(blank=True, help_text='Кожен пункт з нового рядка', verbose_name='Що входить у послугу')),
                ('risks', models.TextField(blank=True, help_text='Кожен пункт з нового рядка', verbose_name='Типові помилки / ризики')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('tags', models.ManyToManyField(blank=True, related_name='services', to='content.tag', verbose_name='Теми')),
            ],
            options={
                'verbose_name': 'Послуга (Замовникам/Учасникам)',
                'verbose_name_plural': 'Послуги (Замовникам/Учасникам)',
                'ordering': ['audience', 'order'],
                'unique_together': {('audience', 'slug')},
            },
        ),
    ]
