# Generated by Django 5.2.7 on 2026-09-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationservice',
            name='client_provides',
            field=models.TextField(blank=True, verbose_name='Що надає клієнт'),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='cta_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='duration',
            field=models.CharField(blank=True, max_length=120, verbose_name='Строк'),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='not_included',
            field=models.TextField(blank=True, verbose_name='Що не входить'),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='price',
            field=models.CharField(blank=True, max_length=120, verbose_name='Вартість / від'),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='problem',
            field=models.TextField(blank=True, verbose_name='Яку проблему вирішуємо'),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='result_format',
            field=models.CharField(blank=True, max_length=255, verbose_name='Формат результату'),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='urgent_available',
            field=models.BooleanField(default=False, verbose_name='Можливе термінове виконання'),
        ),
        migrations.AddField(
            model_name='service',
            name='client_provides',
            field=models.TextField(blank=True, verbose_name='Що надає клієнт'),
        ),
        migrations.AddField(
            model_name='service',
            name='cta_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.CharField(blank=True, max_length=120, verbose_name='Строк виконання'),
        ),
        migrations.AddField(
            model_name='service',
            name='not_included',
            field=models.TextField(blank=True, verbose_name='Що не входить у послугу'),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.CharField(blank=True, max_length=120, verbose_name='Вартість / від'),
        ),
        migrations.AddField(
            model_name='service',
            name='result_format',
            field=models.CharField(blank=True, max_length=255, verbose_name='Формат результату'),
        ),
        migrations.AddField(
            model_name='service',
            name='urgent_available',
            field=models.BooleanField(default=False, verbose_name='Можливе термінове виконання'),
        ),
    ]
