# Generated by Django 5.2.7 on 2026-09-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Ім'я")),
                ('contact', models.CharField(max_length=200, verbose_name='Контакт (email/телефон/telegram)')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='Тема звернення')),
                ('tender_link', models.URLField(blank=True, verbose_name='Посилання на закупівлю (Prozorro)')),
                ('message', models.TextField(verbose_name='Опис ситуації')),
                ('consent', models.BooleanField(default=False, verbose_name='Згода на обробку персональних даних')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False, verbose_name='Опрацьовано')),
            ],
            options={
                'verbose_name': 'Звернення',
                'verbose_name_plural': 'Звернення',
                'ordering': ['-created_at'],
            },
        ),
    ]
