# Generated by Django 5.2.7 on 2026-09-08 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='audience',
            field=models.CharField(choices=[('zamovnyk', 'Я — замовник'), ('uchasnyk', 'Я — учасник')], default='zamovnyk', max_length=20, verbose_name='Аудиторія'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Крайній строк'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='help_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='Вид допомоги'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='urgent',
            field=models.BooleanField(default=False, verbose_name='Терміново'),
        ),
        migrations.CreateModel(
            name='ConsultationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='consultations/%Y/%m/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='consultations.consultationrequest')),
            ],
        ),
    ]
