# Generated by Django 5.2.7 on 2026-09-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultationrequest_audience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='request_number',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Номер звернення'),
        ),
    ]
