# Generated by Django 5.2.7 on 2026-09-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_consultationrequest_request_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='response_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Телефон'), ('telegram', 'Telegram'), ('viber', 'Viber')], default='email', max_length=20, verbose_name='Зручний спосіб відповіді'),
        ),
    ]
