# Generated by Django 5.2.17 on 2026-09-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок кейсу')),
                ('situation', models.TextField(verbose_name='Ситуація')),
                ('action', models.TextField(verbose_name='Дія')),
                ('result', models.TextField(verbose_name='Результат')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейси (Про мене)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=255, verbose_name='Email або Telegram')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Підписник розсилки',
                'verbose_name_plural': 'Підписники розсилки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telegram', models.URLField(blank=True, verbose_name='Посилання на Telegram')),
                ('viber', models.URLField(blank=True, verbose_name='Посилання на Viber')),
                ('response_sla', models.CharField(default='Орієнтовний термін відповіді — 2 робочі дні', max_length=255, verbose_name='Орієнтовний термін відповіді')),
                ('consultation_format_note', models.TextField(default="Консультації надаються письмово. Типові питання вже мають відповіді в розділах «Роз'яснення» та «Питання та відповіді». Індивідуальна консультація по вашій ситуації — платна, вартість уточнюється після опису ситуації.", verbose_name='Пояснення формату консультацій')),
                ('about_intro', models.TextField(blank=True, verbose_name='Вступний текст "Про мене"')),
                ('experience_years', models.CharField(blank=True, max_length=100, verbose_name='Досвід (наприклад "7+ років")')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
