# Generated by Django 5.2.7 on 2026-09-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='confidentiality_note',
            field=models.TextField(blank=True, verbose_name='Принцип конфіденційності'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='expert_education',
            field=models.TextField(blank=True, verbose_name='Освіта та сертифікати'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='expert_experience',
            field=models.TextField(blank=True, verbose_name='Фактичний досвід'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='expert_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ім’я та прізвище експерта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='expert_photo',
            field=models.ImageField(blank=True, null=True, upload_to='expert/', verbose_name='Фото експерта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='expert_specialization',
            field=models.CharField(blank=True, max_length=255, verbose_name='Спеціалізація'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='legal_provider_details',
            field=models.TextField(blank=True, verbose_name='Реквізити надавача платних послуг'),
        ),
    ]
