# Generated by Django 5.2.7 on 2026-09-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_confidentiality_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['order'], 'verbose_name': 'Кейс', 'verbose_name_plural': 'Кейси (Команда ІдеЯ)'},
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_intro',
            field=models.TextField(blank=True, verbose_name='Вступний текст «Команда ІдеЯ»'),
        ),
    ]
