# Generated by Django 5.2.17 on 2026-09-04 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type', models.CharField(choices=[('clarification', "Роз'яснення"), ('news', 'Новина')], default='clarification', max_length=20, verbose_name='Тип матеріалу')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('audience', models.CharField(choices=[('zamovnykam', 'Замовникам'), ('uchasnykam', 'Учасникам'), ('both', 'Усім')], default='both', max_length=20, verbose_name='Для кого')),
                ('summary', models.TextField(blank=True, verbose_name='Короткий опис (для списків)')),
                ('short_answer', models.TextField(blank=True, verbose_name='Коротка відповідь')),
                ('legal_basis', models.TextField(blank=True, verbose_name='Нормативна опора')),
                ('action_algorithm', models.TextField(blank=True, verbose_name='Алгоритм дій')),
                ('wording', models.TextField(blank=True, verbose_name='Робоче формулювання')),
                ('body', models.TextField(blank=True, verbose_name='Текст новини / додатковий текст')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показувати в дайджесті на Головній')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Матеріал (роз’яснення / новина)',
                'verbose_name_plural': "Роз'яснення та новини",
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Назва теми')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тема (тег)',
                'verbose_name_plural': 'Теми (теги)',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Питання')),
                ('answer', models.TextField(verbose_name='Відповідь')),
                ('audience', models.CharField(choices=[('zamovnykam', 'Замовникам'), ('uchasnykam', 'Учасникам'), ('both', 'Усім')], default='both', max_length=20, verbose_name='Для кого')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярне питання (показувати на Головній)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('related_article', models.ForeignKey(blank=True, limit_choices_to={'article_type': 'clarification'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_from_article', to='content.article', verbose_name="Пов'язане роз'яснення")),
                ('tags', models.ManyToManyField(blank=True, related_name='faq_items', to='content.tag', verbose_name='Теми')),
            ],
            options={
                'verbose_name': 'Питання та відповідь',
                'verbose_name_plural': 'Питання та відповіді',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='content.tag', verbose_name='Теми'),
        ),
    ]
