# Generated by Django 5.2.7 on 2026-09-08 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_article_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Автор / експерт'),
        ),
        migrations.AddField(
            model_name='article',
            name='current_as_of',
            field=models.DateField(blank=True, null=True, verbose_name='Актуально станом на'),
        ),
        migrations.AddField(
            model_name='article',
            name='exceptions_risks',
            field=models.TextField(blank=True, verbose_name='Винятки та ризики'),
        ),
        migrations.AddField(
            model_name='article',
            name='legal_basis_reference',
            field=models.CharField(blank=True, max_length=500, verbose_name='Пункт і номер нормативного акта'),
        ),
        migrations.AddField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='content.article', verbose_name='Пов’язані матеріали'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='Посилання на першоджерело'),
        ),
        migrations.CreateModel(
            name='OfficialExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_date', models.DateField(verbose_name='Дата документа')),
                ('document_number', models.CharField(max_length=120, verbose_name='Номер документа')),
                ('title', models.CharField(max_length=500, verbose_name='Офіційна назва')),
                ('summary', models.TextField(verbose_name='Короткий опис')),
                ('source_page_url', models.URLField(verbose_name='Посилання на картку документа')),
                ('source_file_url', models.URLField(verbose_name='Пряме посилання на файл')),
                ('checked_at', models.DateTimeField(auto_now=True, verbose_name='Остання перевірка посилання')),
                ('is_current', models.BooleanField(default=True, verbose_name='Актуальне')),
                ('practical_comment', models.ForeignKey(blank=True, limit_choices_to={'article_type': 'clarification'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_sources', to='content.article', verbose_name='Практичний коментар ІдеЯ')),
                ('tags', models.ManyToManyField(blank=True, related_name='official_explanations', to='content.tag', verbose_name='Теми')),
            ],
            options={
                'verbose_name': 'Офіційне роз’яснення Мінекономіки',
                'verbose_name_plural': 'Офіційні роз’яснення Мінекономіки',
                'ordering': ['-document_date', '-id'],
            },
        ),
    ]
