# Generated by Django 5.2.7 on 2026-09-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_article_author_article_current_as_of_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='changes_document',
            field=models.CharField(blank=True, max_length=500, verbose_name='Документ, яким внесено зміни'),
        ),
        migrations.AddField(
            model_name='article',
            name='effective_from',
            field=models.DateField(blank=True, null=True, verbose_name='Дата набрання чинності'),
        ),
        migrations.AddField(
            model_name='article',
            name='template_url',
            field=models.URLField(blank=True, verbose_name='Посилання на файл або шаблон'),
        ),
        migrations.AddField(
            model_name='article',
            name='what_to_do',
            field=models.TextField(blank=True, verbose_name='Що потрібно зробити замовнику або учаснику'),
        ),
    ]
