# Generated by Django 5.2.7 on 2026-09-08 13:30

from django.db import migrations, models


def replace_both_audience(apps, schema_editor):
    Article = apps.get_model('content', 'Article')
    FAQItem = apps.get_model('content', 'FAQItem')
    Article.objects.filter(audience='both').update(audience='zamovnykam')
    FAQItem.objects.filter(audience='both').update(audience='zamovnykam')


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_article_changes_document_article_effective_from_and_more'),
    ]

    operations = [
        migrations.RunPython(replace_both_audience, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='article',
            name='audience',
            field=models.CharField(choices=[('zamovnykam', 'Замовникам'), ('uchasnykam', 'Учасникам')], default='zamovnykam', max_length=20, verbose_name='Для кого'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='audience',
            field=models.CharField(choices=[('zamovnykam', 'Замовникам'), ('uchasnykam', 'Учасникам')], default='zamovnykam', max_length=20, verbose_name='Для кого'),
        ),
    ]
