# Generated by Django 5.2.7 on 2026-09-08 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_article_audience_alter_faqitem_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialexplanation',
            name='current_text_url',
            field=models.URLField(blank=True, verbose_name='Посилання на чинний текст з #Text'),
        ),
        migrations.AddField(
            model_name='officialexplanation',
            name='document_type',
            field=models.CharField(choices=[('law', 'Закон'), ('resolution', 'Постанова'), ('order', 'Наказ'), ('procedure', 'Порядок'), ('guideline', 'Настанова')], default='resolution', max_length=20, verbose_name='Вид документа'),
        ),
        migrations.AddField(
            model_name='officialexplanation',
            name='keywords',
            field=models.TextField(blank=True, help_text='Слова через кому', verbose_name='Ключові слова'),
        ),
        migrations.AddField(
            model_name='officialexplanation',
            name='previous_revision_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Підпис попередньої редакції'),
        ),
        migrations.AddField(
            model_name='officialexplanation',
            name='previous_text_url',
            field=models.URLField(blank=True, verbose_name='Посилання на попередню редакцію'),
        ),
        migrations.AddField(
            model_name='officialexplanation',
            name='status',
            field=models.CharField(choices=[('current', 'Чинний'), ('invalid', 'Втратив чинність'), ('upcoming', 'Набирає чинності')], default='current', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='officialexplanation',
            name='checked_at',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Перевірено'),
        ),
        migrations.AlterField(
            model_name='officialexplanation',
            name='source_file_url',
            field=models.URLField(verbose_name='Офіційне посилання'),
        ),
    ]
