# Generated by Django 5.2.7 on 2026-09-08 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_officialexplanation_current_text_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormativeAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('law', 'Закон'), ('resolution', 'Постанова'), ('order', 'Наказ'), ('procedure', 'Порядок'), ('guideline', 'Настанова')], default='resolution', max_length=20, verbose_name='Вид документа')),
                ('status', models.CharField(choices=[('current', 'Чинний'), ('invalid', 'Втратив чинність'), ('upcoming', 'Набирає чинності')], default='current', max_length=20, verbose_name='Статус')),
                ('document_date', models.DateField(verbose_name='Дата документа')),
                ('document_number', models.CharField(max_length=120, verbose_name='Номер документа')),
                ('title', models.CharField(max_length=500, verbose_name='Офіційна назва')),
                ('summary', models.TextField(verbose_name='Короткий опис')),
                ('keywords', models.TextField(blank=True, help_text='Слова через кому', verbose_name='Ключові слова')),
                ('current_text_url', models.URLField(verbose_name='Посилання на чинний текст з #Text')),
                ('previous_text_url', models.URLField(blank=True, verbose_name='Посилання на попередню редакцію')),
                ('previous_revision_label', models.CharField(blank=True, max_length=255, verbose_name='Підпис попередньої редакції')),
                ('checked_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Перевірено')),
                ('tags', models.ManyToManyField(blank=True, related_name='normative_acts', to='content.tag', verbose_name='Напрями')),
            ],
            options={
                'verbose_name': 'Нормативно-правовий акт',
                'verbose_name_plural': 'Нормативно-правові акти',
                'ordering': ['-document_date', '-id'],
            },
        ),
    ]
